// range.js · The Filter AI · FREE BUILD (generated by build-free.js, do not edit)
// Stage 1 of the Practice Range is open. The other stages are locked stubs
// that carry only a title, an intro and a count.

const RANGE = {
  "intro": "You have spent seven units learning to recognise these attacks on paper. That is the harder half. This is where you go to run them. The order below is deliberate: browser toys first, then indirect injection, then agents and MCP, then the self-hosted ranges where you can take something apart properly. Everything listed is free or runs on your own machine.",
  "credit": {
    "text": "Resource universe curated by Arcanum Information Security",
    "org": "Arcanum Information Security",
    "url": "https://arcanum-sec.com",
    "indexUrl": "https://arcanum-sec.github.io/ai-sec-resources/",
    "note": "The selection, ordering and notes on this page are ours. The underlying directory of resources is theirs, and it is worth reading in full."
  },
  "totalCount": 45,
  "sections": [
    {
      "id": "start",
      "title": "Start here",
      "intro": "Open a tab, type, break something. No install, no API key, no account. If you have never landed a working injection, do these in order and you will land one within the hour.",
      "items": [
        {
          "title": "Gandalf",
          "url": "https://gandalf.lakera.ai/",
          "level": "Beginner to Advanced",
          "host": "Online",
          "note": "The one everybody starts with. Talk a wizard into handing over a password across seven tightening levels. The later levels add an output filter, which is where it stops being a party trick and starts teaching you something."
        },
        {
          "title": "HackMerlin",
          "url": "https://hackmerlin.io/",
          "level": "Beginner to Intermediate",
          "host": "Online",
          "note": "The same idea as Gandalf with different defences, so it is a genuinely useful second run rather than a repeat. Good for testing whether your first tricks generalise or whether you just memorised one prompt."
        },
        {
          "title": "GPT Prompt Attack",
          "url": "https://gpa.43z.one/",
          "level": "Beginner",
          "host": "Online",
          "note": "Extract the key in as few characters as possible. The character budget is the whole lesson: it forces you to work out which word in your payload is actually doing the work."
        },
        {
          "title": "Doublespeak",
          "url": "https://doublespeak.chat/",
          "level": "Beginner to Intermediate",
          "host": "Online",
          "note": "A gatekeeper bot that will not say its own name. Escalating levels, browser only. Closer to the roleplay and narrative framings from Unit 2 than the blunt override attacks."
        },
        {
          "title": "Prompt Airlines",
          "url": "https://promptairlines.com/",
          "level": "Intermediate",
          "host": "Online",
          "note": "Wiz built this one. Five challenges against a customer service chatbot, ending in a free ticket. It is the first target on this list with a real business function behind it, which changes what a successful attack looks like."
        },
        {
          "title": "PromptInjects",
          "url": "https://promptinjects.com/",
          "level": "Beginner to Intermediate",
          "host": "Online",
          "note": "Each level is a small themed app with a flag buried in the system prompt. No account needed. A quick way to get reps in across several different framings in one sitting."
        }
      ]
    },
    {
      "id": "indirect",
      "title": "Indirect and document injection",
      "intro": "Unit 3 territory. The attacker never talks to the model. They write something the model will later read: a web page, an email, a support ticket, a PDF. These targets are where that gap gets exploitable rather than theoretical.",
      "locked": true,
      "lockedCount": 5,
      "items": []
    },
    {
      "id": "rag",
      "title": "RAG and vector poisoning",
      "intro": "Unit 5. Nobody attacks the model here. They attack what the model retrieves. These are the targets where you can plant a document, watch it get chunked and embedded, and then see it come back out of a query weeks later.",
      "locked": true,
      "lockedCount": 3,
      "items": []
    },
    {
      "id": "agents",
      "title": "Agents and MCP",
      "intro": "Unit 4 and Unit 6. Once a model can call tools, an injection stops being a text problem and becomes a permissions problem. This is the fastest moving corner of the field and the one worth the most in a bounty right now.",
      "locked": true,
      "lockedCount": 6,
      "items": []
    },
    {
      "id": "ranges",
      "title": "Self-hosted ranges, for going deep",
      "intro": "Docker, a local model, and an afternoon. These give you something the hosted games cannot: you can read the source, change the defence, and rerun the attack to see what actually stopped it. That loop is where the understanding comes from.",
      "locked": true,
      "lockedCount": 7,
      "items": []
    },
    {
      "id": "tools",
      "title": "Tools to run against targets",
      "intro": "Manual attacks teach you the shape of the problem. Tooling is how you cover a real system in a working week. All open source, all runnable locally, and the last one is a defence you should also be attacking.",
      "locked": true,
      "lockedCount": 7,
      "items": []
    },
    {
      "id": "money",
      "title": "Competitions and bug bounties",
      "intro": "Where the skill becomes paid work. Competitions give you a leaderboard and a deadline. Bounty programmes give you scope, a real target, and a legal basis for touching it. Read the scope document before you touch anything.",
      "locked": true,
      "lockedCount": 8,
      "items": []
    },
    {
      "id": "reading",
      "title": "Worth reading",
      "intro": "Three references you will come back to. Not labs, but the things that make the labs make sense.",
      "locked": true,
      "lockedCount": 3,
      "items": []
    }
  ]
};

const RANGE_SECTIONS = RANGE.sections;
const RANGE_ITEMS    = RANGE.sections.flatMap(s => s.items);
const RANGE_COUNT    = RANGE_ITEMS.length;
